const projectCollection = {
  bsonType: "object",
  required: [
    "accountCodes",
    "projectName",
    "teamLead",
    "relNonRel",
    "technology",
    "teamSplit",
    "trackingId",
    "misPeriod",
    "itemName",
    "fscr",
    "fscrName",
    "currentStatus",
    "assignedTo",
    "totalEffort",
    "totalEffortForMonth",
    "approvalStatus",
    "requestReceivedDate",
    "requestedByBSA",
    "devPlannedStartDate",
    "devPlannedEndDate",
    "uatRelPlannedDate",
    "assignedDevelopmentDate",
    "tsDocument",
    "misGroup"
  ],
  properties: {
    trackingId: { bsonType: "string" },
    misPeriod: { bsonType: "string" },
    poNumber: { bsonType: "string" },
    tentativePoDate: { bsonType: "string" },
    poDescription: { bsonType: "string" },
    tcuCode: { bsonType: "string" },
    teamLead: { bsonType: "string" },
    projectName: { bsonType: "string" },
    relNonRel: { bsonType: "string" },
    teamSplit: { bsonType: "string" },
    accountCodes: { bsonType: "string" },
    technology: { bsonType: "string" },
    fscr: { bsonType: "string" },
    itemName: { bsonType: "string" },
    fscrName: { bsonType: "string" },
    currentStatus: { bsonType: "string" },
    challenge: { bsonType: "string" },
    generalRemark: { bsonType: "string" },
    patch: { bsonType: "string" },
    assignedTo: { bsonType: "string" },
    totalEffort: { bsonType: "number" },
    totalEffortForMonth: { bsonType: "number" },
    effortApprovalBy: { bsonType: "string" },
    effortApprovalDate: { bsonType: "string" },
    approvalStatus: { bsonType: "string" },
    requestReceivedDate: { bsonType: "string" },
    requestedByBSA: { bsonType: "string" },
    walkthoughPlannedDate: { bsonType: "string" },
    devPlannedStartDate: { bsonType: "string" },
    devPlannedEndDate: { bsonType: "string" },
    uatRelPlannedDate: { bsonType: "string" },
    actualWalkthroughDate: { bsonType: "string" },
    assignedDevelopmentDate: { bsonType: "string" },
    actualDevStartDate: { bsonType: "string" },
    actualDevEndDate: { bsonType: "string" },
    uatPromotionSignOffDate: { bsonType: "string" },
    delayedDelivery: { bsonType: "string" },
    reasonForDelay: { bsonType: "string" },
    tsDocument: { bsonType: "string" },
    reviewedBy: { bsonType: "string" },
    promotionDate: { bsonType: "string" },
    promotedBy: { bsonType: "string" },
    promotionTicketNumber: { bsonType: "string" },
    misGroup: { bsonType: "string" },
    invoiceNumber: { bsonType: "string" }
  }
};

module.exports = projectCollection;
